version: '3.9'
services:
  app:
    container_name: app
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: 'yarn dev'
    environment:
      - DB_USER=root
      - DB_PASS=password
      - DB_HOST=db
      - DB_PORT=3306
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
  db:
    image: mysql:8.0.32
    container_name: db
    ports:
      - 33060:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql
  datastore:
    image: busybox
    container_name: datastore
    volumes:
      - db_data:/var/lib/mysql
      - node_modules:/app/node_modules
volumes:
  db_data:
  node_modules:
